[tool.poetry]
name = "slack-alerts"
version = "0.1.0"
description = ""
authors = ["etienne-napoleone <etienne@tomochain.com>"]

[tool.poetry.dependencies]
python = "*"
requests = "^2.20"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
